hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [secured_area]
    connect:
        account_connector: my.oauth_aware.user_provider.service

    fosub:
        username_iterations: 30
        properties:
            github: github_id

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    resource_owners:
        github:
            type:                github
            client_id:           "%env(GITHUB_CLIENT_ID)%"
            client_secret:       "%env(GITHUB_CLIENT_SECRET)%"
            scope:               'user'